### ISSUE TITLE
write-host in scripts blows up

### ISSUE THREAD

**Issue by mikeclayton** [lholman/AutoBot#8] opened 2011-11-23 17:24 UTC
I thought I'd raised this a couple of days ago, but it hasn't appeared here...

Using "write-host" inside scripts caused AutoBot to blow up. I've not got the exact error text, but it was basically saying that the PowerShell host doesn't implement WriteLine.

To reproduce, create a basic script which calls write-host, then ask AutoBot to run it.

**Comment by lholman** [comment] 2011-11-24 09:20
Duplicate of #7

**Closed as completed by lholman** 2011-11-24 09:20 UTC
